name: Build & Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true  # Ensure we fetch all tags

      - name: Build firmware using ESPHome
        uses: esphome/build-action@v6
        with:
          yaml-file: device.yaml

      - name: Check FW versions
        id: check_version
        run: |
          apt-get install -y yq

          FW_VERSION=$(yq '.substitutions.fw_ver' device.yaml)
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")

          if [ $FW_VERSION != $LATEST_TAG ]; then
            echo "new_release=true" >> $GITHUB_OUTPUT
          else
            echo "new_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        if: steps.check_version.outputs.new_release == 'true'
        run: |
          gh release create ${{ steps.extract_fw_version.outputs.FW_VERSION }} device/*.bin --title "Release ${{ steps.extract_fw_version.outputs.FW_VERSION }}"
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
