name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        env:
          POSTGRES_PASSWORD: "123456789abcd"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: list
        run: |
          ls

      - name: Prepare DB
        run: |
          psql -U postgres -tc "CREATE DATABASE test"
        env:
          PGPASSWORD: "123456789abcd"

